/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ConfirmDialogTone } from "./components/confirm-dialog/confirm-dialog.types";
import { FilterChangeDetail } from "./components/filter-select/filter-select.types";
import { SlotAddDetail } from "./components/meal-slot/meal-slot.types";
import { CardOpenDetail, FavoriteToggleDetail } from "./components/recipe-card/recipe-card.types";
import { SearchInputDetail, SearchSubmitDetail } from "./components/search-bar/search-bar.types";
export { ConfirmDialogTone } from "./components/confirm-dialog/confirm-dialog.types";
export { FilterChangeDetail } from "./components/filter-select/filter-select.types";
export { SlotAddDetail } from "./components/meal-slot/meal-slot.types";
export { CardOpenDetail, FavoriteToggleDetail } from "./components/recipe-card/recipe-card.types";
export { SearchInputDetail, SearchSubmitDetail } from "./components/search-bar/search-bar.types";
export namespace Components {
    interface ConfirmDialog {
        /**
          * @default 'Cancel'
         */
        "cancelLabel": string;
        /**
          * @default 'Confirm'
         */
        "confirmLabel": string;
        /**
          * @default 'Are you sure?'
         */
        "heading": string;
        /**
          * @default false
         */
        "open": boolean;
        /**
          * @default 'default'
         */
        "tone": ConfirmDialogTone;
    }
    interface FilterSelect {
        /**
          * @default 'Any'
         */
        "anyLabel": string;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default ''
         */
        "options": string;
        /**
          * @default 'Type to filter options'
         */
        "searchLabel": string;
        /**
          * @default true
         */
        "searchable": boolean;
        /**
          * @default ''
         */
        "value": string;
    }
    interface MealSlot {
        /**
          * @default 'Add meal'
         */
        "addLabel": string;
        "day": string;
        /**
          * @default false
         */
        "isEmpty": boolean;
        "slotLabel": string;
    }
    interface RecipeCard {
        "area"?: string;
        "category"?: string;
        "image"?: string;
        /**
          * @default false
         */
        "isFavorite": boolean;
        /**
          * @default false
         */
        "isOwned": boolean;
        "name": string;
        "recipeId": string;
    }
    interface SearchBar {
        /**
          * @default 'Search recipes'
         */
        "label": string;
        /**
          * @default 'Search recipes…'
         */
        "placeholder": string;
        /**
          * @default ''
         */
        "value": string;
    }
}
export interface ConfirmDialogCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLConfirmDialogElement;
}
export interface FilterSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFilterSelectElement;
}
export interface MealSlotCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMealSlotElement;
}
export interface RecipeCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeCardElement;
}
export interface SearchBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSearchBarElement;
}
declare global {
    interface HTMLConfirmDialogElementEventMap {
        "dialog-confirm": void;
        "dialog-cancel": void;
    }
    interface HTMLConfirmDialogElement extends Components.ConfirmDialog, HTMLStencilElement {
        addEventListener<K extends keyof HTMLConfirmDialogElementEventMap>(type: K, listener: (this: HTMLConfirmDialogElement, ev: ConfirmDialogCustomEvent<HTMLConfirmDialogElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLConfirmDialogElementEventMap>(type: K, listener: (this: HTMLConfirmDialogElement, ev: ConfirmDialogCustomEvent<HTMLConfirmDialogElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLConfirmDialogElement: {
        prototype: HTMLConfirmDialogElement;
        new (): HTMLConfirmDialogElement;
    };
    interface HTMLFilterSelectElementEventMap {
        "filter-change": FilterChangeDetail;
    }
    interface HTMLFilterSelectElement extends Components.FilterSelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFilterSelectElementEventMap>(type: K, listener: (this: HTMLFilterSelectElement, ev: FilterSelectCustomEvent<HTMLFilterSelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFilterSelectElementEventMap>(type: K, listener: (this: HTMLFilterSelectElement, ev: FilterSelectCustomEvent<HTMLFilterSelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFilterSelectElement: {
        prototype: HTMLFilterSelectElement;
        new (): HTMLFilterSelectElement;
    };
    interface HTMLMealSlotElementEventMap {
        "slot-add": SlotAddDetail;
    }
    interface HTMLMealSlotElement extends Components.MealSlot, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMealSlotElementEventMap>(type: K, listener: (this: HTMLMealSlotElement, ev: MealSlotCustomEvent<HTMLMealSlotElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMealSlotElementEventMap>(type: K, listener: (this: HTMLMealSlotElement, ev: MealSlotCustomEvent<HTMLMealSlotElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMealSlotElement: {
        prototype: HTMLMealSlotElement;
        new (): HTMLMealSlotElement;
    };
    interface HTMLRecipeCardElementEventMap {
        "favorite-toggle": FavoriteToggleDetail;
        "card-open": CardOpenDetail;
    }
    interface HTMLRecipeCardElement extends Components.RecipeCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeCardElementEventMap>(type: K, listener: (this: HTMLRecipeCardElement, ev: RecipeCardCustomEvent<HTMLRecipeCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeCardElementEventMap>(type: K, listener: (this: HTMLRecipeCardElement, ev: RecipeCardCustomEvent<HTMLRecipeCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeCardElement: {
        prototype: HTMLRecipeCardElement;
        new (): HTMLRecipeCardElement;
    };
    interface HTMLSearchBarElementEventMap {
        "search-input": SearchInputDetail;
        "search-submit": SearchSubmitDetail;
        "search-clear": void;
    }
    interface HTMLSearchBarElement extends Components.SearchBar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSearchBarElementEventMap>(type: K, listener: (this: HTMLSearchBarElement, ev: SearchBarCustomEvent<HTMLSearchBarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSearchBarElementEventMap>(type: K, listener: (this: HTMLSearchBarElement, ev: SearchBarCustomEvent<HTMLSearchBarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSearchBarElement: {
        prototype: HTMLSearchBarElement;
        new (): HTMLSearchBarElement;
    };
    interface HTMLElementTagNameMap {
        "confirm-dialog": HTMLConfirmDialogElement;
        "filter-select": HTMLFilterSelectElement;
        "meal-slot": HTMLMealSlotElement;
        "recipe-card": HTMLRecipeCardElement;
        "search-bar": HTMLSearchBarElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    interface ConfirmDialog {
        /**
          * @default 'Cancel'
         */
        "cancelLabel"?: string;
        /**
          * @default 'Confirm'
         */
        "confirmLabel"?: string;
        /**
          * @default 'Are you sure?'
         */
        "heading"?: string;
        "onDialog-cancel"?: (event: ConfirmDialogCustomEvent<void>) => void;
        "onDialog-confirm"?: (event: ConfirmDialogCustomEvent<void>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * @default 'default'
         */
        "tone"?: ConfirmDialogTone;
    }
    interface FilterSelect {
        /**
          * @default 'Any'
         */
        "anyLabel"?: string;
        /**
          * @default ''
         */
        "label"?: string;
        "onFilter-change"?: (event: FilterSelectCustomEvent<FilterChangeDetail>) => void;
        /**
          * @default ''
         */
        "options"?: string;
        /**
          * @default 'Type to filter options'
         */
        "searchLabel"?: string;
        /**
          * @default true
         */
        "searchable"?: boolean;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface MealSlot {
        /**
          * @default 'Add meal'
         */
        "addLabel"?: string;
        "day": string;
        /**
          * @default false
         */
        "isEmpty"?: boolean;
        "onSlot-add"?: (event: MealSlotCustomEvent<SlotAddDetail>) => void;
        "slotLabel": string;
    }
    interface RecipeCard {
        "area"?: string;
        "category"?: string;
        "image"?: string;
        /**
          * @default false
         */
        "isFavorite"?: boolean;
        /**
          * @default false
         */
        "isOwned"?: boolean;
        "name": string;
        "onCard-open"?: (event: RecipeCardCustomEvent<CardOpenDetail>) => void;
        "onFavorite-toggle"?: (event: RecipeCardCustomEvent<FavoriteToggleDetail>) => void;
        "recipeId": string;
    }
    interface SearchBar {
        /**
          * @default 'Search recipes'
         */
        "label"?: string;
        "onSearch-clear"?: (event: SearchBarCustomEvent<void>) => void;
        "onSearch-input"?: (event: SearchBarCustomEvent<SearchInputDetail>) => void;
        "onSearch-submit"?: (event: SearchBarCustomEvent<SearchSubmitDetail>) => void;
        /**
          * @default 'Search recipes…'
         */
        "placeholder"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }

    interface ConfirmDialogAttributes {
        "open": boolean;
        "heading": string;
        "confirmLabel": string;
        "cancelLabel": string;
        "tone": ConfirmDialogTone;
    }
    interface FilterSelectAttributes {
        "label": string;
        "value": string;
        "options": string;
        "anyLabel": string;
        "searchable": boolean;
        "searchLabel": string;
    }
    interface MealSlotAttributes {
        "day": string;
        "slotLabel": string;
        "isEmpty": boolean;
        "addLabel": string;
    }
    interface RecipeCardAttributes {
        "recipeId": string;
        "name": string;
        "image": string;
        "category": string;
        "area": string;
        "isFavorite": boolean;
        "isOwned": boolean;
    }
    interface SearchBarAttributes {
        "value": string;
        "placeholder": string;
        "label": string;
    }

    interface IntrinsicElements {
        "confirm-dialog": Omit<ConfirmDialog, keyof ConfirmDialogAttributes> & { [K in keyof ConfirmDialog & keyof ConfirmDialogAttributes]?: ConfirmDialog[K] } & { [K in keyof ConfirmDialog & keyof ConfirmDialogAttributes as `attr:${K}`]?: ConfirmDialogAttributes[K] } & { [K in keyof ConfirmDialog & keyof ConfirmDialogAttributes as `prop:${K}`]?: ConfirmDialog[K] };
        "filter-select": Omit<FilterSelect, keyof FilterSelectAttributes> & { [K in keyof FilterSelect & keyof FilterSelectAttributes]?: FilterSelect[K] } & { [K in keyof FilterSelect & keyof FilterSelectAttributes as `attr:${K}`]?: FilterSelectAttributes[K] } & { [K in keyof FilterSelect & keyof FilterSelectAttributes as `prop:${K}`]?: FilterSelect[K] };
        "meal-slot": Omit<MealSlot, keyof MealSlotAttributes> & { [K in keyof MealSlot & keyof MealSlotAttributes]?: MealSlot[K] } & { [K in keyof MealSlot & keyof MealSlotAttributes as `attr:${K}`]?: MealSlotAttributes[K] } & { [K in keyof MealSlot & keyof MealSlotAttributes as `prop:${K}`]?: MealSlot[K] } & OneOf<"day", MealSlot["day"], MealSlotAttributes["day"]> & OneOf<"slotLabel", MealSlot["slotLabel"], MealSlotAttributes["slotLabel"]>;
        "recipe-card": Omit<RecipeCard, keyof RecipeCardAttributes> & { [K in keyof RecipeCard & keyof RecipeCardAttributes]?: RecipeCard[K] } & { [K in keyof RecipeCard & keyof RecipeCardAttributes as `attr:${K}`]?: RecipeCardAttributes[K] } & { [K in keyof RecipeCard & keyof RecipeCardAttributes as `prop:${K}`]?: RecipeCard[K] } & OneOf<"recipeId", RecipeCard["recipeId"], RecipeCardAttributes["recipeId"]> & OneOf<"name", RecipeCard["name"], RecipeCardAttributes["name"]>;
        "search-bar": Omit<SearchBar, keyof SearchBarAttributes> & { [K in keyof SearchBar & keyof SearchBarAttributes]?: SearchBar[K] } & { [K in keyof SearchBar & keyof SearchBarAttributes as `attr:${K}`]?: SearchBarAttributes[K] } & { [K in keyof SearchBar & keyof SearchBarAttributes as `prop:${K}`]?: SearchBar[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "confirm-dialog": LocalJSX.IntrinsicElements["confirm-dialog"] & JSXBase.HTMLAttributes<HTMLConfirmDialogElement>;
            "filter-select": LocalJSX.IntrinsicElements["filter-select"] & JSXBase.HTMLAttributes<HTMLFilterSelectElement>;
            "meal-slot": LocalJSX.IntrinsicElements["meal-slot"] & JSXBase.HTMLAttributes<HTMLMealSlotElement>;
            "recipe-card": LocalJSX.IntrinsicElements["recipe-card"] & JSXBase.HTMLAttributes<HTMLRecipeCardElement>;
            "search-bar": LocalJSX.IntrinsicElements["search-bar"] & JSXBase.HTMLAttributes<HTMLSearchBarElement>;
        }
    }
}
